name: Build & Deploy Backend

on:
  push:
    paths:
      - 'play-scala/**'
      - 'cloud/backend.Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to ACR
      uses: azure/docker-login@v1
      with:
        login-server: playreactregistry.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -f cloud/backend.Dockerfile -t playreactregistry.azurecr.io/backend:latest .
        docker push playreactregistry.azurecr.io/backend:latest
